### PR TITLE
Replace subspecs by podspecs

### PR DESCRIPTION
**Pull request by navartis**
Main goal:

Fix issue "Multiple commands produce SBTUITestTunnel.framework" as described in 
https://github.com/Subito-it/SBTUITestTunnel/issues/69
Receipts, described in this issue specially in https://github.com/Subito-it/SBTUITestTunnel/issues/69#issuecomment-517613435 does not work

Additional benefits:

1. Fixes https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Installation.md#-installation-issues-framework-not-found
2. Latest version of Cocoapods 1.7.5 does not allow to define "Debug" for pod subspec (for example pod 'SBTUITestTunnelServer', :configurations => ["Debug"])
This is useful for security reasons and helps to reduce size of App Store build.
3. Cocoapods plug in cocoapods-binary https://guides.cocoapods.org/plugins/pre-compiling-dependencies.html does not support precompiling pod subspecs

### CODE REVIEW

**Comment by tcamin** [comment]
Hi! Given that this is a major breaking change I’d rather try to understand if there’s a way to fix the issue with the current setup first.

I’m running the tunnel in multiple projects with the latest Xcode and so far I have not being able to replicate the issue.

Could you share a sample project that shows the problem?

**Comment by navartis** [comment]
> Hi! Given that this is a major breaking change I’d rather try to understand if there’s a way to fix the issue with the current setup first.
> 
> I’m running the tunnel in multiple projects with the latest Xcode and so far I have not being able to replicate the issue.
> 
> Could you share a sample project that shows the problem?

Hi!

You can easily reproduce this error for the version https://github.com/Subito-it/SBTUITestTunnel/releases/tag/4.0.0

Using SBTUITestTunnel-Example inside this repo.

Before running Archive you need to set Team in Signing section of SBTUITestTunnel_Example target
then run Archiving.

For explicit settings for example create ./Example/fastlane/Fastfile
With content:
```
lane :test_archive do
  gym(
    scheme: "SBTUITestTunnel-Example",
    configuration: "Release",
    clean: true,
    include_symbols: true,
    export_method: "ad-hoc",
    output_directory: "./build",
  )
end
```

And run in command line from ./Example directory command
$ fastlane test_archive

Using this receipt you can also check my fix;)

Logicaly it is absolutely strong that error "SBTUITestTunnel.framework" occurs because frameworks for SBTUITestTunnel/Server and SBTUITestTunnel/Client has the same name "SBTUITestTunnel.framework"

**Comment by navartis** [comment]
> I’m running the tunnel in multiple projects with the latest Xcode and so far I have not being able to replicate the issue.

The only case I can imaging is that you are using Installation (Manual) https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Installation.md#installation-manual

or other kind of magic

**Comment by tcamin** [comment]
Hi,  just pushed some changes to master which include among other things the podspec splitting you proposed. Sorry about not merging the PR in directly but in the meantime changes had diverged and I preferred to quickly push the updates avoiding longer back and forths.

Unfortunately I have really limited time for maintaining the repo but the contribution was really appreciated. I hope this finally fixes the building issue you and others have been experiencing.

**Comment by navartis** [comment]
> Hi, just pushed some changes to master which include among other things the podspec splitting you proposed. Sorry about not merging the PR in directly but in the meantime changes had diverged and I preferred to quickly push the updates avoiding longer back and forths.
> 
> Unfortunately I have really limited time for maintaining the repo but the contribution was really appreciated. I hope this finally fixes the building issue you and others have been experiencing.

No problem, Tomas!

Main goal achieved and this is great.

Thank you!

**Pull request closed without merging**
