### PR TITLE
Stubs counting for precise control under testing app

### PR DESCRIPTION
**Pull request by navartis**
Some times app perform redundant requests which causing loss of resources.

With this request, in case if removeAfterIterations != 0 (infinite) was used for request stubbing, it becomes possible to query number of unused stubs using `- (NSDictionary<SBTRequestMatch *, NSNumber *> *)unusedStubsPeekAll` of `SBTUITunneledApplication`

### CODE REVIEW

**Comment by tcamin** [comment]
Hi, thanks for the PR!

If I properly understood the requirements, I think the same result can be achieved with the current implementation by leveraging the monitoring functionality.

Monitoring allows to collect requests as they happen app side and later inspect them, seeing among other things which were stubbed and which not. This is actually very similar to your implementation of `commandUnusedStubsMatchesPeek`.

I've copy pasted your test cases and reimplemented them using the current APIs here: (https://github.com/Subito-it/SBTUITestTunnel/blob/pr/unused_stubs/Example/SBTUITestTunnel_Tests/UnusedStubsPeekAll.swift) adding the following helper method
```
private func unusedStubs(matching match: SBTRequestMatch, removeAfterIterations: Int = 0) -> Int {
    let requests = app.monitoredRequestsPeekAll()
    let unusedCount = max(0, removeAfterIterations - requests.filter { $0.matches(match) && $0.isStubbed }.count)

    return unusedCount
}  
```

This should allow even a more fine-grain control letting you distinguish unused stub per SBTRequestMatch as shown in the last test

```
func testForTwoMatchesAndRemoveAfterTwoIterationsForOneUsedOnce() {
    let firstMatch = SBTRequestMatch(url: "httpbin.org")
    let secondMatch = SBTRequestMatch(url: "go.gl")
    let removeAfterIterations: Int = 2
    app.stubRequests(matching: firstMatch,
                        response: SBTStubResponse(response: ["stubbed": 1]),
                        removeAfterIterations: UInt(removeAfterIterations))
    app.stubRequests(matching: secondMatch,
                        response: SBTStubResponse(response: ["stubbed": 1]),
                        removeAfterIterations: UInt(removeAfterIterations))
    app.monitorRequests(matching: firstMatch)
    app.monitorRequests(matching: secondMatch)

    let result = request.dataTaskNetwork(urlString: "http://httpbin.org/get")
    XCTAssert(request.isStubbed(result))

    let unusedCountFirstMatch = unusedStubs(matching: firstMatch, removeAfterIterations: removeAfterIterations)
    let unusedCountSecondMatch = unusedStubs(matching: secondMatch, removeAfterIterations: removeAfterIterations)
    
    XCTAssertEqual(unusedCountFirstMatch, removeAfterIterations - 1)
    XCTAssertEqual(unusedCountSecondMatch, removeAfterIterations)
}
```

where I can distringuish unuse count for firstMatch and secondMatch separately.

Let me know if this achieves what you need.

**Comment by navartis** [comment]
Tomas, sorry, but you didn’t quite understand everything correctly.

My decision allows to control triggered stubs per every match using method `- (NSDictionary<SBTRequestMatch *, NSNumber *> *)unusedStubsPeekAll` that return dictionary.
And yours in fact allows to control only total count of stubs. Which is not convenient in app with many different concurrent requests at every screen.

Besides in your example `testForTwoMatchesAndRemoveAfterTwoIterationsForOneUsedOnce` we have access to the instance of concrete request of class NetworkRequests which is unreal in real UI Tests.

**Comment by navartis** [comment]
@tcamin 🙏

**Comment by tcamin** [comment]
I’ve been doing some refactoring to cleanup the codebase and simplify the implementation of some older requests (eg https://github.com/Subito-it/SBTUITestTunnel/issues/80) which might also allow doing something similar to what you’re looking for. While I understand and see the convenience of the functionality I believe the current implementation applies to a single specific use case. I would like to keep the public api of the library as simple and general purpose as possible while still allowing, through combination, to cover specific needs.

Stay tuned, I hope to come up with something really soon.

**Comment by navartis** [comment]
Tomas, sorry, but "might"? "similar"? "looking for"? "single specific use case"?

I'm not looking, I implemented feature with tests for it and leave existing tests green. 

And about "I would like to keep the public api of the library as simple and general purpose as possible while still allowing, through combination, to cover specific needs."
I added one specific single responsibility method and you decide that it makes public api noisy?
Really?

Friendly speaking, if you are not ready for contributions, what for you wrote [this](https://github.com/Subito-it/SBTUITestTunnel#contributions)?

**Comment by tcamin** [comment]
I'm sorry you're taking it that way. I'm open to contributions and as you can see your self even very large PRs has been accepted in the past but I'd prefer to keep this on hold, check if the changes that are coming in might suite your case and eventually merge it in afterwards.

**Comment by tcamin** [comment]
To further share the changes that are coming, I’m adding a method to return a dictionary of [SBTRequestMatch: SBTStubResponse] moving the count of iterations into SBTStubResponse.

While this will introduce some breaking changes it should be what you’re looking for adding some long requested features as well. It also simplifies the implementation in many parts.

**Comment by tcamin** [comment]
The changes that are coming in are breaking. I will merge the PR in, tag a release so this can be used with the current API

**Pull request merged**
