### PR TITLE
Add test demonstrating that the time stubbing takes grows exponentially with the amount of stubs to be performed

### PR DESCRIPTION
**Pull request by acecilia**
Hi 👋 

This PR adds tests demonstrating the issue mentioned in https://github.com/Subito-it/SBTUITestTunnel/issues/144

### CODE REVIEW

**Comment by acecilia** [comment]
See how the amount of time it takes to configure 10 stubs grows exponentially with the amount of stubs previously configured. Expectation is that it remains the same:

```
[0.09584498405456543, 0.23393702507019043, 0.42101097106933594, 0.938494086265564]
```

Screenshot 2022-09-16 at 13 19 49

**Comment by tcamin** [comment]
Interesting, I'll take a look at it as soon as possible

**Comment by acecilia** [comment]
😮  I am using 13.4.1 on an M1 macbook

**Comment by acecilia** [comment]
Managed to find out [the root cause](https://github.com/Subito-it/SBTUITestTunnel/issues/144#issuecomment-1249575329). Do you want to merge this tests, or should I decline it?

**Review by tcamin — APPROVED** [review]

**Comment by tcamin** [comment]
It's a nice addition, LGTM

**Pull request merged**
